version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - ./docker/var/log/mysql:/var/log/mysql
      - ./docker/var/lib/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mvc-web-services
      MYSQL_DATABASE: mvc-web-services
      MYSQL_USER: mvc-web-services
      MYSQL_PASSWORD: mvc-web-services
    ports:
      - "3306:3306"